name: Run All Jupyter Notebooks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-ipynbs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: rocketpy_env

      - name: Run All Notebooks
        run: |
          find . -name "*.ipynb" | while read -r notebook; do
            jupyter nbconvert --to notebook --execute "$notebook" --output "$notebook" || exit 1
          done
